### ISSUE TITLE
如何针对不同使用场景快速地切换配置？

### ISSUE THREAD

**Issue by vnimy** [qiin2333/Sunshine-Foundation#19]
我的使用场景是这样的：
我使用的是集显的笔记本，平时带电脑上班，在办公室用集显在午休玩两把，回到家就插上我的显卡坞。

就是这么一个来回切换，每次都要重新选输出显卡、显示器，然后重启服务，确实是比较繁琐，有什么办法或命令可以针对不同场景切换不同的配置呢？

**Comment by vnimy** [comment]
自己写了个批处理，相当有效

**Comment by Sakura-stay** [comment]
大佬能不能出个教程教一下，我也有这个需求，在家的时候是套用iPad当副屏。在外面用手机连了玩游戏

**Comment by vnimy** [comment]
> 大佬能不能出个教程教一下，我也有这个需求，在家的时候是套用iPad当副屏。在外面用手机连了玩游戏

你这个跟我描述的场景不一样啊，我上面描述的是针对主机在不同硬件外设下的使用。

你这个场景是针对客户端在不同网络环境的使用，不过我确实也有你这个场景。
**关于你这个场景：**
- 在家里直接连内网就行；
- 在外面你只需要用zerotier或tailscale就能跟家里的设备组网了，但是手机网络信号影响非常大，最好能用5G信号来连；

**Comment by Sakura-stay** [comment]
不是的，可能我没描述清楚，我连接是没问题的。但是在内网时候当副屏sunshine有一套设置。在外网用手机连的时候sunshine又是另一套设置。我的意思是有没有办法让sunshine识别到这两个社备按照我预设的设置项自动更改。或者说有没有办法能在sunshine里加个设置列表，可以一键切换之前保存的预设呢。

**Comment by vnimy** [comment]
我自己写了一个脚本用来切换，你可以参考下
https://github.com/[vnimy/sunshine-cmds](https://github.com/vnimy/sunshine-cmds)

**Comment by vnimy** [comment]
> 不是的，可能我没描述清楚，我连接是没问题的。但是在内网时候当副屏sunshine有一套设置。在外网用手机连的时候sunshine又是另一套设置。我的意思是有没有办法让sunshine识别到这两个社备按照我预设的设置项自动更改。或者说有没有办法能在sunshine里加个设置列表，可以一键切换之前保存的预设呢。

我自己写了一个脚本用来切换，你可以参考下
https://github.com/vnimy/sunshine-cmds
