### ISSUE TITLE
v2024.1111版本“就是要用虚拟显示器”功能在win10上无法正常启用

### ISSUE THREAD

**Issue by starP-W** [qiin2333/Sunshine-Foundation#21]
系统：Windows10 22h2
虚拟显示器：VDD.23.10.20.2（按照[教程](https://github.com/[qiin2333/sunshine-control-panel](https://github.com/qiin2333/sunshine-control-panel))安装的虚拟显示器）安装完毕后设置对应分辨率并禁用设备。
描述：在面板中设置“就是要用虚拟显示器”，组合状态设定禁用其它显示器仅启用指定显示器，串流时物理显示器不黑屏（不管虚拟显示器是否禁用），查看日志显示启用Virtual Display with HDR失败且重试无效，只能一直保持虚拟显示器启用并手动指定到该显示器。
是否是因为win10下虚拟显示器的名称（Virtual Display Driver by MTT）跟win11的（Virtual Display with HDR）不一样导致的这个选项不能正常生效？

**Comment by Yundi339** [comment]
关闭moonlight[优化游戏设置]选项导致的[Virtual Display with HDR]虚拟显示器崩坏，出现感叹号和031报错的问题，已在sunshine基地版1212版本修复此错误，请出现此问题的用户更新1212版本

**Comment by Yundi339** [comment]
> 系统：Windows10 22h2 虚拟显示器：VDD.23.10.20.2（按照[教程](https://github.com/%5Bqiin2333/sunshine-control-panel%5D(https://github.com/qiin2333/sunshine-control-panel))安装的虚拟显示器）安装完毕后设置对应分辨率并禁用设备。 描述：在面板中设置“就是要用虚拟显示器”，组合状态设定禁用其它显示器仅启用指定显示器，串流时物理显示器不黑屏（不管虚拟显示器是否禁用），查看日志显示启用Virtual Display with HDR失败且重试无效，只能一直保持虚拟显示器启用并手动指定到该显示器。 是否是因为win10下虚拟显示器的名称（Virtual Display Driver by MTT）跟win11的（Virtual Display with HDR）不一样导致的这个选项不能正常生效？

关闭moonlight[优化游戏设置]选项导致的[Virtual Display with HDR]虚拟显示器崩坏，出现感叹号和031报错的问题，已在sunshine基地版1212版本修复此错误，请出现此问题的用户更新1212版本，并且一定要开启moonlight[优化游戏设置]选项

**Comment by mmyddd** [comment]
> > 系统：Windows10 22h2 虚拟显示器：VDD.23.10.20.2（按照[教程](https://github.com/%5Bqiin2333/sunshine-control-panel%5D(https://github.com/qiin2333/sunshine-control-panel))安装的虚拟显示器）安装完毕后设置对应分辨率并禁用设备。描述：在面板中设置“就是要用虚拟显示器”，组合状态设定禁用其它显示器仅启用指定显示器，串流时物理显示器不黑屏（不管虚拟显示器是否禁用），查看日志显示启用Virtual Display with HDR失败且重试无效，只能一直保持虚拟显示器启用并手动指定到该显示器。是否是因为win10下虚拟显示器的名称（Virtual Display Driver by MTT）跟win11的（Virtual Display with HDR）不一样导致的这个选项不能正常生效？
> 
> 关闭moonlight[优化游戏设置]选项导致的[Virtual Display with HDR]虚拟显示器崩坏，出现感叹号和031报错的问题，已在sunshinebase版1212版本修复此错误，请出现此问题的用户更新1212版本，并且一定要开启moonlight[优化游戏设置]选项

我没有找到1212版本

**Comment by starP-W** [comment]
已经升级到1227版本，此问题得到解决
